// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCySfNMrnrDFOSJYMcACZGOJaBWB9Y8cI',
    appId: '1:967335157253:web:fa70278f0162966890c66c',
    messagingSenderId: '967335157253',
    projectId: 'flutter-pwa-d76bd',
    authDomain: 'flutter-pwa-d76bd.firebaseapp.com',
    storageBucket: 'flutter-pwa-d76bd.firebasestorage.app',
    measurementId: 'G-J3HV2R0ZVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJguQiGd-t462izQIxui-Er_HYc9eQx8',
    appId: '1:967335157253:android:9c2e8165560b2f7190c66c',
    messagingSenderId: '967335157253',
    projectId: 'flutter-pwa-d76bd',
    storageBucket: 'flutter-pwa-d76bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbig7v9HS6h8ukynA-0eGaCkdfOBtbWRQ',
    appId: '1:967335157253:ios:a9c0c276bc277a9c90c66c',
    messagingSenderId: '967335157253',
    projectId: 'flutter-pwa-d76bd',
    storageBucket: 'flutter-pwa-d76bd.firebasestorage.app',
    iosBundleId: 'com.example.flutterPwaDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbig7v9HS6h8ukynA-0eGaCkdfOBtbWRQ',
    appId: '1:967335157253:ios:a9c0c276bc277a9c90c66c',
    messagingSenderId: '967335157253',
    projectId: 'flutter-pwa-d76bd',
    storageBucket: 'flutter-pwa-d76bd.firebasestorage.app',
    iosBundleId: 'com.example.flutterPwaDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCySfNMrnrDFOSJYMcACZGOJaBWB9Y8cI',
    appId: '1:967335157253:web:f6a6ecd9e3b16ff990c66c',
    messagingSenderId: '967335157253',
    projectId: 'flutter-pwa-d76bd',
    authDomain: 'flutter-pwa-d76bd.firebaseapp.com',
    storageBucket: 'flutter-pwa-d76bd.firebasestorage.app',
    measurementId: 'G-ZW0LTSVNGK',
  );
}
